# mysql connect configuration
mysql:
  path: '127.0.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'tgoj'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
